### PR TITLE
8.x 1.x

### PR DESCRIPTION
**Pull request by danielbeeke**
I have changed the libraries syntax, and for me the entity validator was creating erros. That is why I have set the requirement of the title to false.

### CODE REVIEW

**Comment by juliencarnot** [comment]
Hi, 
Thanks for this pull request, I tried it and it solves some of the problems I had with Jose's version, but I [still have some errors, especially on a custom content type](https://www.drupal.org/node/2380433#comment-10809626). Any hints would be appreciated!
Thanks, Julien

**Comment by nalipaz** [comment]
This doesn't fix the issue for me. The node I am trying to submit still suggests that I have left the title null.

**Comment by juliencarnot** [comment]
@nalipaz : did you check your [content-type config](https://www.drupal.org/node/2380433#comment-10857280)?

**Comment by nalipaz** [comment]
```
$ drush @fsed status
 Drupal version                  :  8.0.5
```

```
$ drush @fsed pmi token
 Extension        :  token                                                                     
 Project          :  token                                                                     
 Type             :  module                                                                    
 Title            :  Token                                                                     
 Description      :  Provides a user interface for the Token API and some missing core tokens. 
 Version          :  8.x-1.0-alpha2                                                            
 Date             :  2016-01-21                                                                
 Package          :  Other                                                                     
 Core             :  8.x                                                                       
 PHP              :  5.5.9                                                                     
 Status           :  enabled                                                                   
 Path             :  modules/token                                                             
 Schema version   :  8000                                                                      
 Requires         :  none                                                                      
 Required by      :  pathauto                                                                  
 Permissions      :  none                                                                      
 Configure        :  None
```

```
 [22]   :  core.base_field_override.node.fsed_entry.title
uuid: 18a0efd9-4bba-48ec-b002-2ea33e081402
langcode: en
status: true
required: false
dependencies: {  }
_core:
  default_config_hash: 7klS5IWXrwzVaPpYZFAs6wcx8U2FF1X73OfrtTsvuvE
id: fallback
label: 'Fallback date format'
locked: true
pattern: 'D, m/d/Y - H:i'
```

**Comment by nalipaz** [comment]
Okay, false alarm. Seems it was caching the config override when I edited it with drush. I edited from the UI and it was still set to true, it was fixed after I reimported it.

**Pull request closed without merging**
